# Generated by Django 5.2.1 on 2025-07-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_shipment_delivery_window'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='sender_addres',
            new_name='sender_address',
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_window',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
